### PR TITLE
feat: add completion cmd

### LINKED ISSUE #16: add auto completion of sub commands
We should have a way to autocomplete sub commands (using tab) and flags so that it is easier for users.

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

fixes #16

### CODE REVIEW

**Comment by developer-guy** [comment]
kindly ping @RinkiyaKeDad

**Comment by RinkiyaKeDad** [comment]
Apologies, this skipped my radar! 🙏  @developer-guy would it be possible for you to add a video showing how the autocompletion looks in action? Thanks a lot for this!

**Comment by developer-guy** [comment]
no worries 🙋🏻‍♂️ it'll look the following 
Screen Shot 2022-05-11 at 10 02 24

**Comment by RinkiyaKeDad** [comment]
Looks great, thanks for working on this!

**Review by RinkiyaKeDad — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
